# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Encode-LaTeX
version:      0.1
version_from: lib/Encode/LaTeX.pm
installdirs:  site
requires:
    HTML::Entities:                0.1
    Pod::LaTeX:                    0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
